steam_cmd = "./steamcmd/steamcmd.exe"       # path to steamcmd (.exe or .sh)
output_dir = "./downloads"                # directory to place generated files
appid = "224260"

# only allow these files to be downloaded
# never allow everything unless you understand the security risks!
whitelist = [
    "maps/*.nmo",
    "maps/*.nav",
    "maps/*.txt",
    "maps/*.bsp",
    "maps/maphacks/**/*.txt"
]