steam_cmd = "path/to/steamcmd.sh"       # path to steamcmd (.exe or .sh)
output_dir = "path/to/output/dir"       # directory to place generated files
appid = "224260"                        # game AppID, e.g. 440 (TF2), 730 (CS:GO)

# only allow these files to be downloaded
# never allow everything unless you understand the security risks!
whitelist = [
    "maps/*.nmo",
    "maps/*.nav",
    "maps/*.txt",
    "maps/*.bsp",
    "maps/maphacks/**/*.txt"
]
